all: tcp_client tcp_server_to_upper

tcp_client: tcp_client.c
	gcc tcp_client.c -o ./build/tcp_client

tcp_server_to_upper: tcp_server_to_upper.c
	gcc tcp_server_to_upper.c -o ./build/tcp_server_to_upper
