all: udp_client udp_client_sendto udp_server udp_server_to_upper

udp_client: udp_client.c
	gcc udp_client.c -o build/udp_client

udp_client_sendto: udp_client_sendto.c
	gcc udp_client_sendto.c -o build/udp_client_sendto

udp_server: udp_server.c
	gcc udp_server.c -o build/udp_server

udp_server_to_upper: udp_server_to_upper.c
	gcc udp_server_to_upper.c -o build/udp_server_to_upper
